FROM python:3.12

RUN mkdir scripts

COPY scripts/ scripts/

WORKDIR scripts

RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y cron

COPY crontab /etc/cron.d/mycron

RUN chmod 0644 /etc/cron.d/mycron

RUN touch /var/log/cron.log

CMD ["cron", "-f"]