CREATE TABLE IF NOT EXISTS User(
    uid INT PRIMARY KEY AUTOINCREMENT,
    email VARCHAR(255) UNIQUE,
    first_name VARCHAR(255),
    last_name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS GeneartedHeadlines(
    gid INT PRIMARY KEY AUTOINCREMENT,
    headline_text VARCHAR(255),
    sentiment DECIMAL(10, 2)
    tid INT,
    cid INT,
    FOREIGN KEY (cid) REFERENCES Company(cid),
    FOREIGN KEY (tid) REFERENCES Topic(tid)
)

CREATE TABLE IF NOT EXISTS Company(
    cid INT PRIMARY KEY AUTOINCREMENT,
    name VARCHAT(255) UNIQUE,
    tid INT,
    FOREIGN KEY (tid) REFERENCES Topic(tid)
)

CREATE TABLE IF NOT EXISTS Topic(
    tid INT PRIMARY KEY AUTOINCREMENT,
    topic_type VARCHAR(255) UNIQUE
)